---
title: "Multiple Values"
author: John Waller
date: '2022-06-21'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Multiple Values}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

There are some differences in how functions across **rgbif** behave with respect to many values given to a single parameter. Typically as a user does need to worry about these details, but it can sometimes make a difference. 

```r
# multiple API requests 
occ_search(taxonKey=c(1,212))
occ_data(taxonKey=c(1,212))

# single API request 
occ_search(taxonKey="1;212"))
occ_data(taxonKey="1;212"))
```

In `occ_search`, there are some parameters you can pass multiple values to in a vector, each value of which produces a **different** request `c("a","b")`. Some parameters allow multiple values to be passed in the **same** request  in a semicolon separated string `"a;b"`. Only one argument at a time can have multiple values in different requests. 

```
# works
occ_search(taxonKey="1;2",basisOfRecord = c("PRESERVED_SPECIMEN","LIVING_SPECIMEN","MATERIAL_CITATION"))
occ_search(occurrenceStatus=c("PRESENT","ABSENT"))

# will give error 
occ_search(taxonKey=c(1,2),basisOfRecord = c("PRESERVED_SPECIMEN","LIVING_SPECIMEN","MATERIAL_CITATION"))
occ_search(occurrenceStatus="PRESENT;ABSENT")
```

When using different requests `c("a","b")`, you will get back a list equal to the value of your vector. To extract data from multiple different requests, you will need something like the following. 

```r

occ_search(taxonKey=c(1,2))[[1]]$data

```

The following table describes whether an argument for `occ_search` or `occ_data` will take multiple values in the same request. 


| arg           | different| same |
|---------------|----------|------|
|basisOfRecord  | X        |X  |
|classKey       | X        |X|
|country        | X        |X|
|familyKey      | X        |X|
|genusKey          | X| X|
|identifiedByID    | X| X|
|kingdomKey        | X| X|
|license           | X| X|
|locality          | X| X|
|catalogNumber     | X| X|
|collectionCode    | X| X|
|continent         | X| X|
|datasetKey        | X| X|
|establishmentMeans| X| X|
|speciesKey| X| X|
|establishmentMeans| X| X|
|degreeOfEstablishment| X| X|
|protocol| X| X|
|license| X| X|
|organismId| X| X|
|publishingOrg| X| X|
|stateProvince| X| X|
|waterBody| X| X|
|locality| X| X|
|basisOfRecord| X| X|
|gadmGid| X| X|
|verbatimScientificName| X| X|
|eventId| X| X|
|identifiedBy| X| X|
|networkKey| X| X|
|occurrenceId| X| X|
|iucnRedListCategory| X| X|
|lifeStage| X| X|
|geometry| X| X|
|institutionCode| X| X|
|mediaType| X| X|
|orderKey| X| X|
|organismId| X| X|
|phylumKey| X| X|
|protocol| X| X|
|publishingCountry| X| X|
|publishingOrg| X| X|
|recordedBy| X| X|
|recordedByID| X| X|
|recordNumber| X| X|
|scientificName| X| X|
|stateProvince| X| X|
|subgenusKey| X| X|
|taxonKey| X| X|
|typeStatus| X| X|
|waterBody| X| X|
|depth| X|
|limit| X|
|q| X|
|year| X|
|repatriated| X|
|lastInterpreted| X|
|decimalLatitude| X|
|decimalLongitude| X|
|coordinateUncertaintyInMeters| X|
|organismQuantity| X|
|organismQuantityType| X|
|relativeOrganismQuantity| X|
|isInCluster| X|
|occurrenceStatus|X|
