context("predicate builders: pred")
test_that("pred", {
  aa <- pred("taxonKey", 7228682)
  expect_is(aa, "occ_predicate")
  expect_is(unclass(aa), "list")
  expect_named(aa, c("type", "key", "value"))
  expect_is(aa$type, "character")
  expect_equal(unclass(aa$type), "equals")
  expect_equal(unclass(aa$key), "TAXON_KEY")
  expect_equal(unclass(aa$value), "7228682")

  bb <- pred("elevation", 5000, ">")
  expect_is(bb, "occ_predicate")
  expect_is(unclass(bb), "list")
  expect_named(bb, c("type", "key", "value"))
  expect_is(bb$type, "character")
  expect_equal(unclass(bb$type), "greaterThan")
})
test_that("pred fails well", {
  expect_error(pred(), "argument \"key\" is missing")
  expect_error(pred(key = "taxonKey"), "argument \"value\" is missing")
  expect_error(pred("a", "b"), "'key' not in acceptable set")
  expect_error(pred(5, "b"), "key must be of class character")
  expect_error(pred("a", 5, 4), "type must be of class character")
})

context("predicate builders: pred_multi")
test_that("pred_multi", {
  taxon_ids <- c(2977832, 2977901, 2977966, 2977835)
  
  aa <- pred_multi("taxonKey", taxon_ids, "or")
  expect_is(aa, "occ_predicate")
  expect_is(unclass(aa), "list")
  expect_named(aa, c("type", "predicates"))
  expect_is(aa$type, "character")
  expect_equal(unclass(aa$type), "or")
  expect_is(aa$predicates, "list")
  expect_equal(length(aa$predicates), length(taxon_ids))

  bb <- pred_multi("taxonKey", taxon_ids, "in")
  expect_is(bb, "occ_predicate")
  expect_is(unclass(bb), "list")
  expect_named(bb, c("type", "key", "values"))
  expect_equal(unclass(bb$type), "in")
  expect_equal(length(bb$values), length(taxon_ids))
})
test_that("pred_multi fails well", {
  expect_error(pred_multi(), "argument \"key\" is missing")
  expect_error(pred_multi(key = "taxonKey"), "argument \"value\" is missing")
  expect_error(pred_multi("a", "b"), "'key' not in acceptable set")
  expect_error(pred_multi(5, "b"), "key must be of class character")
  expect_error(pred_multi("a", 5, 4), "'type' must be one of: or, in")
})
