context("deprecated functions")

test_that("returns a warning", {
  expect_that(density_spplist(originisocountrycode = "CO"), gives_warning())
  expect_that(densitylist(originisocountrycode = "CA"), gives_warning())
  expect_that(occurrencecount(scientificname = 'Accipiter erythronemius', coordinatestatus = TRUE), gives_warning())
  expect_that(occurrencedensity(), gives_warning())
  expect_that(occurrenceget(key = 13749100), gives_warning())
  expect_that(occurrencelist(scientificname = 'Puma concolor', coordinatestatus = TRUE, maxresults = 40), gives_warning())
  expect_that(occurrencelist_all(scientificname = 'Aristolochia serpentaria', coordinatestatus = TRUE), gives_warning())
  expect_that(occurrencelist_many(c('Accipiter erythronemius', 'Junco hyemalis', 'Aix sponsa'), coordinatestatus = TRUE, maxresults = 100), gives_warning())
  expect_that(providers('University of Texas-Austin'), gives_warning())
  expect_that(resources('Flora'), gives_warning())
  expect_that(taxoncount(rank = 'family'), gives_warning())
  expect_that(taxonget(51780668), gives_warning())
  expect_that(taxonsearch(scientificname = 'Abies', rank="genus"), gives_warning())
  expect_that(gbifmap_dens(densitylist(originisocountrycode="US"), mapdatabase="usa"), gives_warning())
  expect_that(gbifmap_list(occurrencelist(scientificname = 'Accipiter erythronemius', coordinatestatus = TRUE)), gives_warning())
})